{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "IDP.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "IDP.fullname" . }}
  endpoints:
    - path: {{ .Values.serviceMonitor.path }}
      port: {{ .Values.serviceMonitor.port }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
